from __future__ import annotations

from video_agent.server.mcp_tools_auth import authenticate_agent_tool
from video_agent.server.mcp_tools_memory import (
    clear_session_memory_tool,
    disable_agent_memory_tool,
    get_agent_memory_tool,
    get_session_memory_tool,
    list_agent_memories_tool,
    promote_session_memory_tool,
    query_agent_memories_tool,
    summarize_session_memory_tool,
)
from video_agent.server.mcp_tools_task import (
    accept_best_version_tool,
    cancel_video_task_tool,
    create_video_task_tool,
    get_failure_contract_tool,
    get_metrics_snapshot_tool,
    get_quality_score_tool,
    get_recovery_plan_tool,
    get_runtime_status_tool,
    get_scene_spec_tool,
    get_task_events_tool,
    get_video_result_tool,
    get_video_task_tool,
    list_video_tasks_tool,
    retry_video_task_tool,
    revise_video_task_tool,
)
from video_agent.server.mcp_tools_thread import (
    append_video_turn_tool,
    create_video_thread_tool,
    get_video_thread_surface_tool,
    list_video_thread_participants_tool,
    remove_video_thread_participant_tool,
    request_video_explanation_tool,
    request_video_revision_tool,
    select_video_result_tool,
    upsert_video_thread_participant_tool,
)
from video_agent.server.mcp_tools_workflow import (
    apply_review_decision_tool,
    get_review_bundle_tool,
    list_workflow_memory_recommendations_tool,
    list_workflow_participants_tool,
    pin_workflow_memory_tool,
    remove_workflow_participant_tool,
    unpin_workflow_memory_tool,
    upsert_workflow_participant_tool,
)

__all__ = [
    "accept_best_version_tool",
    "append_video_turn_tool",
    "apply_review_decision_tool",
    "authenticate_agent_tool",
    "cancel_video_task_tool",
    "clear_session_memory_tool",
    "create_video_task_tool",
    "create_video_thread_tool",
    "disable_agent_memory_tool",
    "get_agent_memory_tool",
    "get_failure_contract_tool",
    "get_metrics_snapshot_tool",
    "get_quality_score_tool",
    "get_recovery_plan_tool",
    "get_review_bundle_tool",
    "get_runtime_status_tool",
    "get_scene_spec_tool",
    "get_session_memory_tool",
    "get_task_events_tool",
    "get_video_result_tool",
    "get_video_task_tool",
    "get_video_thread_surface_tool",
    "list_agent_memories_tool",
    "list_video_tasks_tool",
    "list_video_thread_participants_tool",
    "list_workflow_memory_recommendations_tool",
    "list_workflow_participants_tool",
    "pin_workflow_memory_tool",
    "promote_session_memory_tool",
    "query_agent_memories_tool",
    "remove_video_thread_participant_tool",
    "remove_workflow_participant_tool",
    "request_video_explanation_tool",
    "request_video_revision_tool",
    "retry_video_task_tool",
    "revise_video_task_tool",
    "select_video_result_tool",
    "summarize_session_memory_tool",
    "unpin_workflow_memory_tool",
    "upsert_video_thread_participant_tool",
    "upsert_workflow_participant_tool",
]
